### ISSUE TITLE
Requirements failed on Debian 5.18.16-1

### ISSUE THREAD

**Issue by gringer** [comprna/radian#3]
Radian is not installing on my system because the requested tensorflow version is too low:

```
gringer@musculus:~/install/radian$ pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Collecting attrdict~=2.0.1
  Using cached attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)
Collecting biopython~=1.79
  Using cached biopython-1.79-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
Collecting keras-tcn~=3.5.0
  Using cached keras_tcn-3.5.0-py3-none-any.whl (13 kB)
Requirement already satisfied: matplotlib~=3.6.1 in /home/gringer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (3.6.1)
Collecting numpy~=1.19.5
  Using cached numpy-1.19.5.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ont-fast5-api~=4.1.0 in /home/gringer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (4.1.0)
Collecting pysam~=0.19.1
  Using cached pysam-0.19.1-cp310-cp310-manylinux_2_24_x86_64.whl (15.2 MB)
Collecting PyYAML~=6.0
  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
Requirement already satisfied: scikit-learn~=1.1.2 in /home/gringer/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (1.1.2)
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4.4 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.11.0rc0, 2.11.0rc1)
ERROR: No matching distribution found for tensorflow~=2.4.4
gringer@musculus:~/install/radian$ uname -a
Linux musculus 5.18.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1 (2022-08-10) x86_64 GNU/Linux
```

I changed the version to 2.9.2 (i.e. `tensorflow ~= 2.9.2`), and it got past that (but I'm expecting that there will need to be some code changes as well)... but I have further issues:

```
ERROR: Cannot install -r requirements.txt (line 10), -r requirements.txt (line 2), -r requirements.txt (line 3), -r requirements.txt (line 4), -r requirements.txt (line 6), -r requirements.txt (line 9) and numpy~=1.19.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy~=1.19.5
    biopython 1.79 depends on numpy
    keras-tcn 3.5.0 depends on numpy
    matplotlib 3.6.1 depends on numpy>=1.19
    ont-fast5-api 4.1.0 depends on numpy>=1.16
    scikit-learn 1.1.2 depends on numpy>=1.17.3
    tensorflow 2.9.2 depends on numpy>=1.20

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

So I changed the numpy requirements as well, to `numpy >= 1.20`. This allowed it to *install* without error:
```
attrdict~=2.0.1
biopython~=1.79
keras-tcn~=3.5.0
matplotlib~=3.6.1
numpy>=1.20
ont-fast5-api~=4.1.0
pysam~=0.19.1
PyYAML~=6.0
scikit-learn~=1.1.2
tensorflow~=2.9.2 # Requires cuDNN 8.1, CUDA 11.2
textdistance~=4.5.0
```

`basecall.py` will run, but not complete, presumably due to slightly different library requirements:

```
gringer@musculus:~/install/radian/radian$ python3 radian/basecall.py data out_dir
2022-10-22 17:14:17.123853: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-22 17:14:17.123874: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/gringer/install/radian/radian/basecall.py", line 14, in <module>
    from utilities import get_config, setup_local
  File "/home/gringer/install/radian/radian/utilities.py", line 7, in <module>
    from attrdict import AttrDict
  File "/home/gringer/.local/lib/python3.10/site-packages/attrdict/__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "/home/gringer/.local/lib/python3.10/site-packages/attrdict/mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by gringer** [comment]
I modified my local `attrdict` installation to change `from collections import Mapping` lines to `from collections.abc import Mapping`, and radian proceeded further. Presumably that change is not scalable, and an alternative approach should be used. It's now complaining about a model file that can't be found:

```
gringer@musculus:~/install/radian/radian$ python3 basecall.py data out_dir
2022-10-22 17:28:12.506364: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-22 17:28:12.506384: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/gringer/install/radian/radian/basecall.py", line 145, in <module>
    main()
  File "/home/gringer/install/radian/radian/basecall.py", line 50, in main
    with open(args.rna_model, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/rnamodel_12mer_pc.json'
gringer@musculus:~/install/radian/radian$ ls models/
sig2seq.h5  sig2seq.yaml
```

So... I guess that's where I end for today. I can't find this model anywhere in the installation (i.e. same issue as #1)

**Comment by a-sneddon** [comment]
Hi @gringer 

Thanks for the updates.  #1 has now been resolved, so you should be able to proceed with testing.  The requirements file lists the package versions we have tested on thus far, this may be loosened after further testing.

Please let me know if you're able to basecall now, or if there are further issues.

Thanks,

**Comment by gringer** [comment]
Yes, I've been able to basecall. For the reads I've been trying it on, I've been getting some matches to the target sequence, but most reads are unmappable (this is possibly related to me not using a proper RNA model). I'm fine with that; it's great to see some degree of consistency with what I expect, even at this early stage of development.

**Comment by a-sneddon** [comment]
Thanks, glad to hear you have been able to basecall.

It's also worth noting that we were aiming here to investigate the utility of an RNA model for basecalling, so the signal-to-sequence model was not heavily optimised (as we were looking at the differential with/without RNA model).  Further work on the signal-to-sequence model will potentially improve accuracy and increase mapping rate.  Also, the RNA model we provide has been generated on human data, but other organisms may be supported in the future.

Thanks for checking out the repo!
